### ISSUE TITLE
RpmITCase.java:41-48: I've checked that this test...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#85]
The puzzle `69-ac25d152` from #69 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/493153a41dfc9dcae2bb43d8af290adf7d7acf47/src/test/java/com/artipie/rpm/RpmITCase.java#L41-L48

The puzzle was created by Kirill on 08-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#85](https://github.com/artipie/rpm-adapter/issues/85) assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/dee86f56-e6eb-4fca-bf47-b59cdb203e68); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by dgarus** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/85#issuecomment-611510631))

@dgarus The user @dgarus[/z](https://www.0crat.com/u/dgarus) resigned from [#85](https://github.com/artipie/rpm-adapter/issues/85), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/85#issuecomment-611510631))

@dgarus Job refused in 17 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#85](https://github.com/artipie/rpm-adapter/issues/85) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1d7ff39d-0836-40f3-9a2d-5be3c08597c6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/85#issuecomment-612409650))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#85](https://github.com/artipie/rpm-adapter/issues/85), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/85#issuecomment-612414870))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#85](https://github.com/artipie/rpm-adapter/issues/85) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @dgarus[/z](https://www.0crat.com/u/dgarus): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%2385%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#85](https://github.com/artipie/rpm-adapter/issues/85) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8b5fe7d8-52a9-4989-9615-8286bb8924a6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/85#issuecomment-613192573))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#85](https://github.com/artipie/rpm-adapter/issues/85), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@7d3334767964, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [75758f7f-378c-4f77-9e71-2be94acfd9cf](https://www.0crat.com/footprint/CT2E6TK9B/75758f7f-378c-4f77-9e71-2be94acfd9cf), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [a4c9eee0-69c1-45f0-b656-dcddcd5316ff](https://www.0crat.com/footprint/CT2E6TK9B/a4c9eee0-69c1-45f0-b656-dcddcd5316ff), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [e377a4a1-d84a-4660-add6-29d48eaeb1ee](https://www.0crat.com/footprint/CT2E6TK9B/e377a4a1-d84a-4660-add6-29d48eaeb1ee), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@7d3334767964, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [777446f1-f799-4143-8813-8e7fd030ef68](https://www.0crat.com/footprint/CT2E6TK9B/777446f1-f799-4143-8813-8e7fd030ef68), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@7d3334767964, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [f1701d16-0459-4b1d-a5f6-6f156de0196d](https://www.0crat.com/footprint/CT2E6TK9B/f1701d16-0459-4b1d-a5f6-6f156de0196d), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [637cb141-0121-4436-91fd-6cb3dee7724c](https://www.0crat.com/footprint/CT2E6TK9B/637cb141-0121-4436-91fd-6cb3dee7724c), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [79e2dd59-4552-482c-9c6e-b468d2050c95](https://www.0crat.com/footprint/CT2E6TK9B/79e2dd59-4552-482c-9c6e-b468d2050c95), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [47ad1188-f767-42ed-9e44-ee5f9eca40b7](https://www.0crat.com/footprint/CT2E6TK9B/47ad1188-f767-42ed-9e44-ee5f9eca40b7), Type: "Start order"

**Comment by victornoel** [comment]
@g4s8 this one seems blocked in a loop or whatever...

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@7d3334767964, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [1ac2c086-9405-4cf5-9cd1-3d7b268f9534](https://www.0crat.com/footprint/CT2E6TK9B/1ac2c086-9405-4cf5-9cd1-3d7b268f9534), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [9996e06f-3c92-47e4-8dc9-43f3f253df2e](https://www.0crat.com/footprint/CT2E6TK9B/9996e06f-3c92-47e4-8dc9-43f3f253df2e), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@7d3334767964, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [11664fc8-7d19-451c-8a1c-895ae0360be2](https://www.0crat.com/footprint/CT2E6TK9B/11664fc8-7d19-451c-8a1c-895ae0360be2), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [d5856cca-1b31-4b5f-a074-43fcc9aea637](https://www.0crat.com/footprint/CT2E6TK9B/d5856cca-1b31-4b5f-a074-43fcc9aea637), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [3de0d374-d117-446c-84a4-7143cf5fa11a](https://www.0crat.com/footprint/CT2E6TK9B/3de0d374-d117-446c-84a4-7143cf5fa11a), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@8362b1b91be7, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [ee0276d5-0394-4944-b6b2-b0c44c69513e](https://www.0crat.com/footprint/CT2E6TK9B/ee0276d5-0394-4944-b6b2-b0c44c69513e), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@8362b1b91be7, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [7de9daef-7218-4474-b6ab-e32ae80f9ec1](https://www.0crat.com/footprint/CT2E6TK9B/7de9daef-7218-4474-b6ab-e32ae80f9ec1), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@8362b1b91be7, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [b422f1ed-8591-45a3-9227-de24b4f23084](https://www.0crat.com/footprint/CT2E6TK9B/b422f1ed-8591-45a3-9227-de24b4f23084), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@8362b1b91be7, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [476c986e-682e-457b-b8ee-09ff109985f0](https://www.0crat.com/footprint/CT2E6TK9B/476c986e-682e-457b-b8ee-09ff109985f0), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@d83d88cd6ffd, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-orders.xsl says: The order for job "gh:artipie/maven-adapter#74" exists in orders.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [0cf42f28-a61c-4a35-b393-3c213e92d9a6](https://www.0crat.com/footprint/CT2E6TK9B/0cf42f28-a61c-4a35-b393-3c213e92d9a6), Type: "Start order"

**Comment by HDouss** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/85#issuecomment-617152533))

@HDouss This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#85](https://github.com/artipie/rpm-adapter/issues/85) is [in scope](http://www.zerocracy.com/policy.html#14) for 13days
  * The role is `DEV`
  * The job is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss) for [4hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @dgarus[/z](https://www.0crat.com/u/dgarus): User was resigned from the ticket
    * @victornoel[/z](https://www.0crat.com/u/victornoel): User was resigned from the ticket
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%2385%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by HDouss** [comment]
@0crat refuse, this test does not seem to work. There isn't even a dir called "rpms" in resources or classpath in general.

**Comment by 0crat** [comment]
> @0crat refuse, this test does not seem to work. There isn't even a dir called "rpms" in resources... ([here](https://github.com/artipie/rpm-adapter/issues/85#issuecomment-617167844))

@HDouss Can't understand "refuse,", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `elect` Trigger election for ticket
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by HDouss** [comment]
@0crat refuse This test does not seem to work. There isn't even a dir called "rpms" in resources or classpath in general.

**Comment by 0crat** [comment]
> @0crat refuse This test does not seem to work. There isn't even a dir called "rpms" in resources ... ([here](https://github.com/artipie/rpm-adapter/issues/85#issuecomment-617171803))

@HDouss The user @hdouss[/z](https://www.0crat.com/u/hdouss) resigned from [#85](https://github.com/artipie/rpm-adapter/issues/85), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse This test does not seem to work. There isn't even a dir called "rpms" in resources ... ([here](https://github.com/artipie/rpm-adapter/issues/85#issuecomment-617171803))

@HDouss Job refused in 4 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#85](https://github.com/artipie/rpm-adapter/issues/85) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7a6522b6-2dc1-4e9e-84c4-9f4cb7f3da16); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 This test doesn't work:
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@paulodamaso the test was fixed in https://github.com/artipie/rpm-adapter/pull/153 (to speed up it locally, you can use `HUNDRED` bundle instead of `THOUSAND`, see enums in test)

**Comment by paulodamaso** [comment]
@0crat wait for #157 merge

**Comment by paulodamaso** [comment]
@g4s8 Merged, please close

**Comment by 0pdd** [comment]
The puzzle `69-ac25d152` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#166](https://github.com/artipie/rpm-adapter/issues/166) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#166](https://github.com/artipie/rpm-adapter/issues/166) is solved here.
